version: 2


sources:
  - name: gz_raw_data
    schema: gz_raw_data
    tables:
      - name: raw_gz_product
        identifier: raw_gz_product
        description: Product details for Greenweez, including purchase prices.
        columns:
          - name: products_id
            description: Unique identifier for each product.
            tests:
              - unique
              - not_null

      - name: raw_gz_ship
        identifier: raw_gz_ship
        description: Shipping information for orders, including costs and fees.
        columns:
          - name: orders_id
            description: Unique identifier for each order (linked to sales table).
            tests:
              - unique
              - not_null