version: 2

sources:
  - name: gz_raw_data
    schema: raw_gz_sales  
    tables:
      - name: raw_gz_sales
        identifier: raw_gz_sales  
        description: Sales data for Greenweez, one row per product_id in each order_id.
        columns:
          - name: date_date
            description: The date of the purchase.
          - name: orders_id
            description: Foreign key to the ship table.
          - name: pdt_id
            description: Foreign key to the products table.
          - name: revenue
            description: The amount paid by the customer for the product.
          - name: quantity
            description: The quantity of products purchased for a given order.